[package]
name = "beton-sdk"
description = "Rust-Client-SDK für die beton-API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
beton-core.workspace = true
beton-proto.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }
tokio-tungstenite.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
