import { expect, PUSH_ASK, test } from './fixtures'

test('WEB-018 AC1: Freigabe-Karte, „Erlauben“ setzt fort, „Ablehnen“ liefert deny mit Kommentar', async ({ daemon, page }) => {
  const allowId = await daemon.session(PUSH_ASK, 'Erlauben')
  await daemon.login(page, `/s/${allowId}`)
  await page.getByLabel('Nachricht').fill('Bitte pushen')
  await page.getByLabel('Nachricht').press('Enter')
  const card = page.getByTestId('approval-card')
  await expect(card).toBeVisible()
  await expect(card).toContainText('git push origin main')
  await card.getByRole('button', { name: 'Erlauben' }).click()
  await expect(page.getByText('Push erledigt.')).toBeVisible()
  await expect(page.getByTestId('tool-card')).toHaveAttribute('data-status', 'completed')

  const denyId = await daemon.session(PUSH_ASK, 'Ablehnen')
  await page.goto(`${daemon.url}/s/${denyId}`)
  await page.getByLabel('Nachricht').fill('Bitte pushen')
  await page.getByLabel('Nachricht').press('Enter')
  const denyCard = page.getByTestId('approval-card')
  await denyCard.getByLabel('Kommentar an das Modell (nur beim Ablehnen)').fill('Erst die Tests laufen lassen')
  await denyCard.getByRole('button', { name: 'Ablehnen' }).click()
  await expect(page.getByText('Push abgelehnt.')).toBeVisible()
  await expect(denyCard).toContainText('Kommentar: Erst die Tests laufen lassen')
  const resolved = (await daemon.events(denyId)).find((e) => e.type === 'approval.resolved')
  expect(resolved?.payload).toMatchObject({ decision: 'deny', comment: 'Erst die Tests laufen lassen' })
})

test('WEB-018 AC2: entscheidet ein Client, zeigt der andere „entschieden“', async ({ daemon, browser }) => {
  const id = await daemon.session(PUSH_ASK, 'Zwei Clients')
  const ctxA = await browser.newContext()
  const ctxB = await browser.newContext()
  const a = await ctxA.newPage()
  const b = await ctxB.newPage()
  await daemon.login(a, `/s/${id}`)
  await daemon.login(b, `/s/${id}`)
  await a.getByLabel('Nachricht').fill('Bitte pushen')
  await a.getByLabel('Nachricht').press('Enter')
  await expect(a.getByTestId('approval-card')).toHaveAttribute('data-decided', 'false')
  await expect(b.getByTestId('approval-card')).toHaveAttribute('data-decided', 'false')
  await a.getByTestId('approval-card').getByRole('button', { name: 'Erlauben' }).click()
  await expect(b.getByTestId('approval-card')).toHaveAttribute('data-decided', 'true')
  await expect(b.getByTestId('approval-card')).toContainText('entschieden')
  await expect(b.getByTestId('approval-card').getByRole('button', { name: 'Erlauben' })).toHaveCount(0)
  await ctxA.close()
  await ctxB.close()
})
