[package]
name = "beton-store"
description = "Persistenz: Event-Log (SQLite/Postgres), Projektionen, Blob-Store."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]


[lints]
workspace = true
