//! Generierte Artefakte aus den Rust-Typen (PROTO-013, QA-006).
//!
//! Rust-Typen sind die einzige Quelle. `cargo xtask codegen` schreibt:
//! - `schemas/v1/events.schema.json` (JSON-Schema via `schemars`)
//! - `packages/sdk-ts/src/gen/*.ts` (TypeScript via `ts-rs`) plus `index.ts`
//!
//! `cargo xtask codegen --check` erzeugt alles in ein temporäres Verzeichnis und vergleicht
//! mit dem eingecheckten Stand; jede Abweichung lässt die CI fehlschlagen.
//! WebSocket-, Tunnel- und OpenAPI-Schemas kommen mit ihren Arbeitspaketen dazu.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use beton_core::event::Event;
use ts_rs::TS;

/// Verzeichnisse, die vollständig generiert werden (veraltete Dateien werden entfernt).
const GENERATED_DIRS: [&str; 2] = ["schemas/v1", "packages/sdk-ts/src/gen"];

const TS_HEADER: &str =
    "// Generiert von `cargo xtask codegen` aus den Rust-Typen. Nicht von Hand ändern.\n";

/// Alle generierten Dateien: Pfad relativ zur Repo-Wurzel → Inhalt.
pub fn generate() -> Result<BTreeMap<PathBuf, String>> {
    let mut files = BTreeMap::new();

    let schema = schemars::schema_for!(Event);
    let mut json = serde_json::to_string_pretty(&schema)?;
    json.push('\n');
    files.insert(PathBuf::from("schemas/v1/events.schema.json"), json);

    let tmp = tempfile::tempdir()?;
    let cfg = ts_rs::Config::new()
        .with_out_dir(tmp.path())
        .with_large_int("number");
    Event::export_all(&cfg).context("TypeScript-Export fehlgeschlagen")?;
    let mut names = Vec::new();
    for path in walk(tmp.path())? {
        let rel = path.strip_prefix(tmp.path())?.to_path_buf();
        let Some(rel_str) = rel.to_str().map(|s| s.replace('\\', "/")) else {
            continue;
        };
        let Some(stem) = rel_str.strip_suffix(".ts").map(str::to_owned) else {
            continue;
        };
        let body = fs::read_to_string(&path)?;
        // ts-rs schreibt einen eigenen Kopf; wir setzen einen einheitlichen.
        let body: String = body
            .lines()
            .filter(|l| !l.starts_with("// This file was generated by"))
            .collect::<Vec<_>>()
            .join("\n");
        files.insert(
            PathBuf::from("packages/sdk-ts/src/gen").join(&rel),
            format!("{TS_HEADER}{}\n", body.trim_start()),
        );
        names.push(stem);
    }
    names.sort();
    let index: String = names
        .iter()
        .map(|n| format!("export type * from './{n}'\n"))
        .collect();
    files.insert(
        PathBuf::from("packages/sdk-ts/src/gen/index.ts"),
        format!("{TS_HEADER}{index}"),
    );
    Ok(files)
}

/// Alle Dateien unter `dir`, rekursiv.
fn walk(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            out.extend(walk(&path)?);
        } else {
            out.push(path);
        }
    }
    Ok(out)
}

/// Schreibt die generierten Dateien und entfernt veraltete in den generierten Verzeichnissen.
pub fn write(root: &Path, files: &BTreeMap<PathBuf, String>) -> Result<()> {
    for dir in GENERATED_DIRS {
        let dir = root.join(dir);
        if dir.exists() {
            for path in walk(&dir)? {
                let rel = path.strip_prefix(root)?.to_path_buf();
                if !files.contains_key(&rel) {
                    fs::remove_file(&path)?;
                }
            }
        }
    }
    for (rel, content) in files {
        let path = root.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, content)?;
    }
    Ok(())
}

/// Abweichungen zwischen generiertem und eingechecktem Stand.
pub fn drift(root: &Path, files: &BTreeMap<PathBuf, String>) -> Result<Vec<String>> {
    let mut problems = Vec::new();
    for (rel, content) in files {
        match fs::read_to_string(root.join(rel)) {
            Ok(existing) if &existing == content => {}
            Ok(_) => problems.push(format!("veraltet: {}", rel.display())),
            Err(_) => problems.push(format!("fehlt: {}", rel.display())),
        }
    }
    for dir in GENERATED_DIRS {
        let dir = root.join(dir);
        if !dir.exists() {
            continue;
        }
        for path in walk(&dir)? {
            let rel = path.strip_prefix(root)?.to_path_buf();
            if !files.contains_key(&rel) {
                problems.push(format!("überzählig: {}", rel.display()));
            }
        }
    }
    Ok(problems)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn proto_013_ac1_committed_artifacts_are_current() {
        let files = generate().unwrap();
        let problems = drift(&crate::repo_root(), &files).unwrap();
        assert!(
            problems.is_empty(),
            "Generierte Dateien sind veraltet – `cargo xtask codegen` ausführen:\n{}",
            problems.join("\n")
        );
    }

    #[test]
    fn proto_013_ac1_drift_is_detected() {
        let files = generate().unwrap();
        let tmp = tempfile::tempdir().unwrap();
        write(tmp.path(), &files).unwrap();
        assert!(drift(tmp.path(), &files).unwrap().is_empty());

        // Feldänderung ohne Neugenerierung: eingecheckte Datei weicht ab.
        let schema = tmp.path().join("schemas/v1/events.schema.json");
        let changed = fs::read_to_string(&schema)
            .unwrap()
            .replace("\"seq\"", "\"sequence\"");
        fs::write(&schema, changed).unwrap();
        // Zusätzliche, nicht mehr erzeugte Datei.
        fs::write(
            tmp.path().join("packages/sdk-ts/src/gen/Alt.ts"),
            "export type Alt = string\n",
        )
        .unwrap();

        let problems = drift(tmp.path(), &files).unwrap();
        assert!(
            problems
                .iter()
                .any(|p| p.contains("veraltet: schemas/v1/events.schema.json")),
            "{problems:?}"
        );
        assert!(
            problems.iter().any(|p| p.contains("überzählig")),
            "{problems:?}"
        );
    }

    #[test]
    fn qa_006_ac1_typescript_contains_event_union() {
        let files = generate().unwrap();
        // `EventPayload` ist in `Event` eingebettet (serde flatten) und steht deshalb in Event.ts.
        let event = files
            .iter()
            .find(|(p, _)| p.ends_with("Event.ts"))
            .map(|(_, c)| c)
            .expect("Event.ts fehlt");
        for (name, _) in beton_core::event::CATALOG {
            assert!(event.contains(&format!("\"type\": \"{name}\"")), "{name} fehlt in Event.ts");
        }
        assert!(files.contains_key(&PathBuf::from("packages/sdk-ts/src/gen/index.ts")));
    }
}
